bitcoin:
	javac Main.java
	java -javaagent:ObjectSizeFetcher.jar Main
clean:
	rm *.class


# javac InstrumentationExample.java ObjectSizeFetcher.java
# jar cvf ObjectSizeFetcher.java ObjectSizeFetcher.class
# jar cmf MANIFEST.MF ObjectSizeFetcher.jar ObjectSizeFetcher.class
# java -javaagent:ObjectSizeFetcher.jar InstrumentationExample
